# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SFTP.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialogButtonBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QProgressBar, QPushButton, QSizePolicy, QStatusBar,
    QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setFixedSize(457, 312)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.user = QLabel(self.centralwidget)
        self.user.setObjectName(u"user")
        self.user.setGeometry(QRect(0, 10, 141, 16))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 20, 451, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.procbtn = QPushButton(self.centralwidget)
        self.procbtn.setObjectName(u"procbtn")
        self.procbtn.setGeometry(QRect(370, 0, 75, 24))
        self.systembtn = QPushButton(self.centralwidget)
        self.systembtn.setObjectName(u"systembtn")
        self.systembtn.setGeometry(QRect(210, 0, 75, 24))
        self.netbtn = QPushButton(self.centralwidget)
        self.netbtn.setObjectName(u"netbtn")
        self.netbtn.setGeometry(QRect(290, 0, 75, 24))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(8, 40, 61, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(8, 70, 61, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(8, 100, 61, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(8, 130, 49, 16))
        self.usernametxt = QLineEdit(self.centralwidget)
        self.usernametxt.setObjectName(u"usernametxt")
        self.usernametxt.setGeometry(QRect(80, 40, 141, 22))
        self.passtxt = QLineEdit(self.centralwidget)
        self.passtxt.setObjectName(u"passtxt")
        self.passtxt.setGeometry(QRect(80, 70, 141, 22))
        self.hostxt = QLineEdit(self.centralwidget)
        self.hostxt.setObjectName(u"hostxt")
        self.hostxt.setGeometry(QRect(80, 100, 141, 22))
        self.porttxt = QLineEdit(self.centralwidget)
        self.porttxt.setObjectName(u"porttxt")
        self.porttxt.setGeometry(QRect(80, 130, 141, 22))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 200, 451, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 220, 421, 23))
        self.progressBar.setValue(24)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(240, 30, 20, 181))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.buttonBox = QDialogButtonBox(self.centralwidget)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(0, 180, 156, 24))
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.files = QToolButton(self.centralwidget)
        self.files.setObjectName(u"files")
        self.files.setGeometry(QRect(170, 180, 71, 22))
        self.filename1 = QLabel(self.centralwidget)
        self.filename1.setObjectName(u"filename1")
        self.filename1.setGeometry(QRect(10, 160, 221, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 40, 49, 16))
        self.user_2 = QLabel(self.centralwidget)
        self.user_2.setObjectName(u"user_2")
        self.user_2.setGeometry(QRect(310, 40, 121, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(260, 80, 61, 16))
        self.user_3 = QLabel(self.centralwidget)
        self.user_3.setObjectName(u"user_3")
        self.user_3.setGeometry(QRect(340, 80, 81, 16))
        self.user_4 = QLabel(self.centralwidget)
        self.user_4.setObjectName(u"user_4")
        self.user_4.setGeometry(QRect(340, 100, 81, 16))
        self.filename2 = QLabel(self.centralwidget)
        self.filename2.setObjectName(u"filename2")
        self.filename2.setGeometry(QRect(260, 130, 191, 16))
        self.sendBtn = QPushButton(self.centralwidget)
        self.sendBtn.setObjectName(u"sendBtn")
        self.sendBtn.setGeometry(QRect(310, 170, 75, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 457, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.user.setText(QCoreApplication.translate("MainWindow", u"User:", None))
        self.procbtn.setText(QCoreApplication.translate("MainWindow", u"Processes", None))
        self.systembtn.setText(QCoreApplication.translate("MainWindow", u"System", None))
        self.netbtn.setText(QCoreApplication.translate("MainWindow", u"Network", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Username:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Host:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.files.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.filename1.setText(QCoreApplication.translate("MainWindow", u"filename", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Sender:", None))
        self.user_2.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Destination", None))
        self.user_3.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.user_4.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.filename2.setText(QCoreApplication.translate("MainWindow", u"Filename:", None))
        self.sendBtn.setText(QCoreApplication.translate("MainWindow", u"Send", None))
    # retranslateUi

