# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainui.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLCDNumber, QLabel,
    QListView, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

from System.UserInfo import user
from System.Disk import disk
from System.MemoryUtility import memory


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.diskData = QListView(self.centralwidget)
        self.diskData.setObjectName(u"diskData")
        self.diskData.setGeometry(QRect(610, 270, 171, 261))
        self.gpuData = QListView(self.centralwidget)
        self.gpuData.setObjectName(u"gpuData")
        self.gpuData.setGeometry(QRect(210, 270, 171, 261))
        self.cpuData = QListView(self.centralwidget)
        self.cpuData.setObjectName(u"cpuData")
        self.cpuData.setGeometry(QRect(10, 270, 171, 261))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(650, 270, 91, 20))
        self.netbtn = QPushButton(self.centralwidget)
        self.netbtn.setObjectName(u"netbtn")
        self.netbtn.setGeometry(QRect(630, 0, 75, 24))
        self.procbtn = QPushButton(self.centralwidget)
        self.procbtn.setObjectName(u"procbtn")
        self.procbtn.setGeometry(QRect(710, 0, 75, 24))
        self.systembtn = QPushButton(self.centralwidget)
        self.systembtn.setObjectName(u"systembtn")
        self.systembtn.setGeometry(QRect(550, 0, 75, 24))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 20, 791, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.user = QLabel(self.centralwidget)
        self.user.setObjectName(u"user")
        self.user.setGeometry(QRect(10, 10, 141, 16))
        self.loginSince = QLabel(self.centralwidget)
        self.loginSince.setObjectName(u"loginSince")
        self.loginSince.setGeometry(QRect(280, 10, 61, 16))
        self.login = QLabel(self.centralwidget)
        self.login.setObjectName(u"login")
        self.login.setGeometry(QRect(350, 10, 171, 16))
        self.cpuTemp = QLCDNumber(self.centralwidget)
        self.cpuTemp.setObjectName(u"cpuTemp")
        self.cpuTemp.setGeometry(QRect(10, 50, 141, 101))
        self.gputmp = QLCDNumber(self.centralwidget)
        self.gputmp.setObjectName(u"gputmp")
        self.gputmp.setGeometry(QRect(220, 100, 141, 101))
        self.fanspeed = QLCDNumber(self.centralwidget)
        self.fanspeed.setObjectName(u"fanspeed")
        self.fanspeed.setGeometry(QRect(420, 100, 141, 101))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(50, 30, 71, 20))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(260, 80, 71, 20))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(460, 80, 71, 20))
        self.hostname = QLabel(self.centralwidget)
        self.hostname.setObjectName(u"hostname")
        self.hostname.setGeometry(QRect(150, 10, 121, 16))
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(610, 280, 171, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(660, 390, 91, 20))
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(610, 400, 171, 20))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(610, 380, 171, 20))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(620, 410, 49, 16))
        self.disktotal = QLabel(self.centralwidget)
        self.disktotal.setObjectName(u"disktotal")
        self.disktotal.setGeometry(QRect(700, 410, 49, 16))
        self.diskused = QLabel(self.centralwidget)
        self.diskused.setObjectName(u"diskused")
        self.diskused.setGeometry(QRect(700, 440, 49, 16))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(620, 440, 49, 16))
        self.dsikfree = QLabel(self.centralwidget)
        self.dsikfree.setObjectName(u"dsikfree")
        self.dsikfree.setGeometry(QRect(700, 470, 49, 16))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(620, 470, 49, 16))
        self.perUsed = QLabel(self.centralwidget)
        self.perUsed.setObjectName(u"perUsed")
        self.perUsed.setGeometry(QRect(700, 500, 49, 16))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(620, 500, 49, 16))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(620, 320, 81, 16))
        self.diskDev = QLabel(self.centralwidget)
        self.diskDev.setObjectName(u"diskDev")
        self.diskDev.setGeometry(QRect(700, 290, 49, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(620, 290, 49, 16))
        self.diskMP = QLabel(self.centralwidget)
        self.diskMP.setObjectName(u"diskMP")
        self.diskMP.setGeometry(QRect(700, 320, 51, 16))
        self.diskData_2 = QListView(self.centralwidget)
        self.diskData_2.setObjectName(u"diskData_2")
        self.diskData_2.setGeometry(QRect(410, 270, 171, 261))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(450, 430, 91, 20))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(420, 470, 49, 16))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(420, 490, 49, 16))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(450, 270, 91, 20))
        self.vmemAvail = QLabel(self.centralwidget)
        self.vmemAvail.setObjectName(u"vmemAvail")
        self.vmemAvail.setGeometry(QRect(500, 310, 51, 16))
        self.smemused = QLabel(self.centralwidget)
        self.smemused.setObjectName(u"smemused")
        self.smemused.setGeometry(QRect(500, 470, 49, 16))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(420, 290, 49, 16))
        self.perUsed_2 = QLabel(self.centralwidget)
        self.perUsed_2.setObjectName(u"perUsed_2")
        self.perUsed_2.setGeometry(QRect(500, 510, 49, 16))
        self.smemFree = QLabel(self.centralwidget)
        self.smemFree.setObjectName(u"smemFree")
        self.smemFree.setGeometry(QRect(500, 490, 49, 16))
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(410, 440, 171, 20))
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(420, 510, 49, 16))
        self.vmemTotal = QLabel(self.centralwidget)
        self.vmemTotal.setObjectName(u"vmemTotal")
        self.vmemTotal.setGeometry(QRect(500, 290, 49, 16))
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(410, 280, 171, 20))
        self.line_9.setFrameShape(QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(420, 310, 81, 16))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(420, 330, 81, 16))
        self.vmemperc = QLabel(self.centralwidget)
        self.vmemperc.setObjectName(u"vmemperc")
        self.vmemperc.setGeometry(QRect(500, 330, 51, 16))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(420, 350, 81, 16))
        self.vmemUsed = QLabel(self.centralwidget)
        self.vmemUsed.setObjectName(u"vmemUsed")
        self.vmemUsed.setGeometry(QRect(500, 350, 51, 16))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(420, 370, 81, 16))
        self.vmemFree = QLabel(self.centralwidget)
        self.vmemFree.setObjectName(u"vmemFree")
        self.vmemFree.setGeometry(QRect(500, 370, 51, 16))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(420, 450, 49, 16))
        self.smemTotal = QLabel(self.centralwidget)
        self.smemTotal.setObjectName(u"smemTotal")
        self.smemTotal.setGeometry(QRect(500, 450, 49, 16))
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(410, 420, 171, 20))
        self.line_10.setFrameShape(QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.vmemActive = QLabel(self.centralwidget)
        self.vmemActive.setObjectName(u"vmemActive")
        self.vmemActive.setGeometry(QRect(500, 390, 51, 16))
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(420, 390, 81, 16))
        self.vmemInact = QLabel(self.centralwidget)
        self.vmemInact.setObjectName(u"vmemInact")
        self.vmemInact.setGeometry(QRect(500, 410, 51, 16))
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(420, 410, 81, 16))
        self.cpuTemp_2 = QLCDNumber(self.centralwidget)
        self.cpuTemp_2.setObjectName(u"cpuTemp_2")
        self.cpuTemp_2.setGeometry(QRect(10, 170, 141, 101))
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(40, 150, 91, 20))
        self.line_11 = QFrame(self.centralwidget)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(210, 280, 171, 20))
        self.line_11.setFrameShape(QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(250, 270, 91, 20))
        self.line_12 = QFrame(self.centralwidget)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(10, 280, 171, 20))
        self.line_12.setFrameShape(QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(50, 270, 91, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.user_label()
        self.user_login()
        self.user_host()
        self.disk_partition_info()
        self.disk_partition_info()
        self.virtual_memory_info()
        self.swap_memory_info()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # These fucctuions will display the user and the login time.
    def user_label(self):
        login_user = user() 
        username = login_user.get_user()
        self.user.setText(username)

    def user_login(self):
        login_date = user()
        login = login_date.get_user_login_date()
        self.login.setText(login)

    def user_host(self):
        user_host = user()
        host = user_host.get_hostname()
        self.hostname.setText(host)

    #functions handle disk related tasks 

    def disk_partition_info(self):
        disk_part = disk()
        partition_info = disk_part.get_disk_partitions()
        self.diskDev.setText(partition_info[0])  
        self.diskMP.setText(partition_info[1])

        # Display usage informatiom
        self.disktotal.setText(str(partition_info[2]))
        self.diskused.setText(str(partition_info[3]))
        self.dsikfree.setText(str(partition_info[4]))
        self.perUsed.setText(str(partition_info[5]))

    #functions to handle memory related tasks 

    def virtual_memory_info(self):
        vir_mem = memory()
        vir_mem_info = vir_mem.get_virtual_memory()
        self.vmemTotal.setText(str(vir_mem_info[0]))
        self.vmemAvail.setText(str(vir_mem_info[1]))
        self.vmemperc.setText(str(vir_mem_info[2]))
        self.vmemUsed.setText(str(vir_mem_info[3]))
        self.vmemFree.setText(str(vir_mem_info[4]))

    def swap_memory_info(self):
        swap_mem = memory()
        swap_mem_info = swap_mem.get_swap_memory()
        self.smemTotal.setText(str(swap_mem_info[0]))
        self.smemused.setText(str(swap_mem_info[1]))
        self.smemFree.setText(str(swap_mem_info[2]))
        self.perUsed_2.setText(str(swap_mem_info[3]))


        
      






    # Functions below handle CPU related tasks. 

    def get_cpu_info():
        return True
    
    def get_disk_info():
        return True
    
    def get_memory_info():
        return True
    
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"System Snake", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Disk Partitions", None))
        self.netbtn.setText(QCoreApplication.translate("MainWindow", u"Network", None))
        self.procbtn.setText(QCoreApplication.translate("MainWindow", u"Processes", None))
        self.systembtn.setText(QCoreApplication.translate("MainWindow", u"System", None))
        self.loginSince.setText(QCoreApplication.translate("MainWindow", u"Last Login:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"CPU TEMP", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU TEMP", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"FAN SPEED", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Disk Usage", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Used:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Free:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Mount Point:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Device:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Swap Memory", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Used:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Free:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Virtual Memory", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Available", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Used:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Free:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Active:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Inactive", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"CPU Frequency", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"GPU Information", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"CPU Information", None))
    # retranslateUi

